### ISSUE TITLE
Prepare new project structure

### ISSUE THREAD

**Issue by Ruskiz** [Ruskiz/link-shortener#1]
You need to prepare next structure of project folder
/back-end
/front-end

where back-end folder will contain node.js express app
and front-end will contain angular-cli app
As result, create Pull request to the master branch

**Comment by RadkevichLiudmila** [comment]
Must the folders be empty or no? empty no add on git

**Comment by Ruskiz** [comment]
)
sure, it cannot be empty. usually, if we want to add some folder to the git we must to add some file to it
by default it is the empty file with ".gitkeep"  name

**Comment by RadkevichLiudmila** [comment]
check)
